### ISSUE TITLE
Issues section does not show issues with the label "feature" and does not have Read More link

### ISSUE THREAD

**Issue by aryanbhasin** [fossasia/gci16.fossasia.org#242]
The issues section currently does not show the issues with the "feature" label, and does not have a Read More text linking to the issue as instructed by this task:
https://codein.withgoogle.com/tasks/5739892873101312/
I would like to work on this

**Comment by abishekvashok** [comment]
See the preview of gci16.fossasia.org
![screenshot_2016-12-06-21-00-25-264_com android chrome](https://cloud.githubusercontent.com/assets/8947010/20931438/143a5764-bbf7-11e6-82d4-750bfb540ee6.png)

It contains both issues and see more button, it further shows only the top ten issues, @aryanbhasin you could further improve it, it currently overflows.

**Comment by oanarosca** [comment]
A 'read more' button is not needed since clicking on a title leads to that issue. However, it is true that this section doesn't show the issues with the feature label, and that there are improvements to be made (some links may not look as expected, the section might not be pretty across all devices). So you can work on this.

**Comment by oanarosca** [comment]
Any updates on this? If you need help, we can gladly help you on Slack. If you no longer want to do this, say it and we'll assign somebody else.

**Comment by gaeun** [comment]
I think we're good to go now... This issue has mostly been addressed.

**Comment by abishekvashok** [comment]
So let's close it
