### ISSUE TITLE
Failing travis Builds

### ISSUE THREAD

**Issue by ankitrgadiya** [fossasia/gci16.fossasia.org#598]
Whenever anybody changes something in index.html intentionally Travis Build fails due to danger.
But then how can we make sure the code is passing all other tests?
But we cannot remove Danger as new contributors for Students/Mentors/Blog tasks are adding code directly to index.html.

So, we have to do something so that Danger checks at the end of the Travis build so that we can make sure that all other tests are passing.

**Comment by abishekvashok** [comment]
@ankitrgadiya just add <-- Safe Edit --> to your PR body and danger won't complain for failed tests. It should be done by gci maintainers and mentors after making sure that he modified the file note to add any student, blogs or logos things [static content instead of dynammic]. So I am closing this.

**Comment by animeshsinghweb** [comment]
@Abhi2424shek @ankitrgadiya 
I guess it is `<!-- Safe Edit -->` and not `<-- Safe Edit -->` as mentioned by @abhi2424shek above, or is both correct?

From **Maintainers.md**:
> To remove that error, add `<!-- Safe Edit -->` somewhere in the PR body.

**Comment by ankitrgadiya** [comment]
@animeshsinghweb It's most probably ```<!-- Safe Edit -->``` @Abhi2424shek typo.
