### ISSUE TITLE
Remove Gray Background

### ISSUE THREAD

**Issue by niccokunzmann** [fossasia/gci16.fossasia.org#607]
I have found that when I resize the window, the banner gets gray bars on top and below.
![image](https://cloud.githubusercontent.com/assets/564768/21296723/759eec3e-c572-11e6-87fa-8d6838318f18.png)

Please remove these gray bars for smaller views.

**Comment by Elgayar** [comment]
I am working on it!

**Comment by Elgayar** [comment]
@niccokunzmann There are two options, either fit the image, and I personally dislike that because it will stretch the image and it will lose quality. The other option is to remove the gray background and put white instead. However, since the radio buttons are white they'll be invisible, I can change the colors, but honestly I believe that when the screen size is reduced, users are probably using the website from a mobile phone and they won't click on radio buttons and would just swipe the slider instead. So they'd be useless to appear. Moreover, there are already right and left arrows that mobile users can still use.

So tell me what you think, see my live link from my repo here to have a clearer view of what I mean: https://elgayar.github.io/gci16.fossasia.org/

If you like it, please confirm with me so that I can make a PR!

Thanks :)

**Comment by niccokunzmann** [comment]
I guess, I would like to see the image fill the currently gray areas.

Maybe than can be achieved with min-height and min-width css attributes.
I do not know.

**Comment by Elgayar** [comment]
It can be, but the image will look awful, stretching it will reduce quality.. @niccokunzmann

**Comment by niccokunzmann** [comment]
In my use-case, I made the picture much smaller. It scaled down. I
think, there will not be a loss of quality in my use-case as I could
look at the picture in twice the size on my desktop.
So, I am not sure if I understand your worries. Also, I personally like
to accept facts and pull-requests and I would like to invite you to
check whether there is no way to make the picture fill the gray area
without loss of quality.

**Comment by Elgayar** [comment]
I'll try to do it, and get back to you.

**Comment by myfrom** [comment]
How about using `background-size: cover`? It will fit the images in container without stretching them

**Comment by robbyoconnor** [comment]
I am closing this as the original issue was resolved
