### ISSUE TITLE
Discussion: What should the constraint for blog images be? 

### ISSUE THREAD

**Issue by robbyoconnor** [fossasia/gci16.fossasia.org#609]
Screenshots aren't square and will skew if we try to make them square...

**Comment by myfrom** [comment]
Blogs should use `background-size: cover` and images should have their original ratio IMO

**Comment by ankitrgadiya** [comment]
@robbyoconnor I think 1920x1080 is fine. I'll reduce the quality a little bit so that size can be small but changing aspect ratio will lead to weird looking screenshots. Also square is not necessary right? 
These are blog post images and they should not look alike student and mentors images is what I think. That's the reason why I changed card size from square to rectangle.

Also I think blurry images are not a sign of good websites.

**Comment by myfrom** [comment]
@ankitrgadiya but remember the cards are squares in small viewport as rectangle wouldn't fit

**Comment by ankitrgadiya** [comment]
@Witus13 I think current ones are fitting well.
![screenshot from 2016-12-19 18-10-12](https://cloud.githubusercontent.com/assets/18071765/21313197/696c2036-c616-11e6-9354-210a9f7d5475.png)

**Comment by abishekvashok** [comment]
@robbyoconnor that's my view too

**Comment by myfrom** [comment]
@ankitrgadiya yes, but they are squares, not rectangles.

Also I would recommend to upload high quality photos but without requiring aspect ratio as they will be cropped and positioned correctly by CSS

**Comment by ankitrgadiya** [comment]
@Witus13 we cannot use high quality images as we're having a lot and it significantly increase the load time. And if we cannot use just css without aspect ratio as we'll get photos of very different sizes. Earlier it was like that and it looks weird as different sizes get fit in same card. That's why I fixed a aspect ration and made cards to solve this problem.

**Comment by myfrom** [comment]
@ankitrgadiya Oh, you're right about the image size. Maybe let's load low quality, blurry photos and then use JavaScript to load better ones when user scrolls down there. I could make a demo. But about ratio I think that `background-size: cover` would do the job.

**Comment by robbyoconnor** [comment]
In this case -- we do not need to check them. So I'll leave the image checker as it is...I'm gonna close this discussion.
