### ISSUE TITLE
Loklak tweet fetcher not working

### ISSUE THREAD

**Issue by abishekvashok** [fossasia/gci16.fossasia.org#638]
![image](https://cloud.githubusercontent.com/assets/8947010/21383721/3788536e-c78d-11e6-89c9-7f16ac2ad6f7.png)

We need to fix it down.

**Comment by kaine119** [comment]
I think the issue lies in [these two lines](https://github.com/fossasia/gci16.fossasia.org/blob/gh-pages/index.html#L1136-L1137). `tweet.js` can't find `loklakFetcher` from `loklak-fetcher.js` because `loklak-fetcher.js` is loaded asynchronously, while `tweet.js` is not. `tweet.js` loads before `loklak-fetcher.js` does.

One possible solution would be just to make `loklak-fetcher.js` load synchronously. Another one would be to write another script that loads the two scripts in succession; something like the Promise function [at the bottom of this answer](http://stackoverflow.com/questions/7718935/load-scripts-asynchronously). Alternatively, put the two scripts together in one file.

Which would be best?

**Comment by abishekvashok** [comment]
Yes that would fix it would you like to do a PR

**Comment by abishekvashok** [comment]
But I have another idea in mind we could avoid loklak fetcher pretty easily, that would reduce code too.

**Comment by kaine119** [comment]
I thought the point of the tweet fetcher section was to showcase loklak?

**Comment by kaine119** [comment]
When was the last commit the section was working? I'd like to see it in it's working state

**Comment by abishekvashok** [comment]
I had a code I will get it to you... For now we would fix it by removing the asynchronous option

**Comment by kaine119** [comment]
alright then.

**Comment by kaine119** [comment]
I'm done, pr #639
