### ISSUE TITLE
Reduce dependency on external services loading unknown extensions

### ISSUE THREAD

**Issue by mariobehling** [fossasia/gci16.fossasia.org#917]
The ism slider seems to want to load extensions on some browser and is not an open source component. Please help to substitute this slider.

**Comment by abishekvashok** [comment]
We could use the bootstrap built in carousel

**Comment by oanarosca** [comment]
@Abhi2424shek that's what I suggested on Slack as well, but since the slider doesn't cause problems anymore, its replacement isn't mandatory. We could, however, substitute it in order to get rid of some javascript, since bootstrap's js is already included and used. @fossasia/gci16-maintainers your opinions?

**Comment by abishekvashok** [comment]
Yep

**Comment by robbyoconnor** [comment]
http://materializecss.com/media.html to replace the slider.
