### ISSUE TITLE
Contributer section does not match the Student and Mentor section. 

### ISSUE THREAD

**Issue by robbyoconnor** [fossasia/gci16.fossasia.org#969]
This is a bug. This can no longer be claimed for GCI but it can be done for the greater good of FOSSASIA! The Contributers was redone but not the other sections...Fix this! There seems to be a border radius on each contributer's card...make students/mentors match this.

**Comment by ankitrgadiya** [comment]
@robbyoconnor apparently this is not a bug. Check this #942.
Although I'm not in favor of the change.
The few changes in past 2-3 days screwed up the look of website.

**Comment by robbyoconnor** [comment]
ankitrgadiya that may be -- but the styling of each student's card now looks weird...make students match the contributers sections -- I like that one. Edited original comment.

**Comment by ankitrgadiya** [comment]
Okay so you want to make cards consistent. I'll do this one

**Comment by Elgayar** [comment]
I made the contributors section's new design, I can make the same with the
students section. Okay?? @robbyoconnor @ankitrgadyia

Ankit R. Gadiya <notifications@github.com> schrieb am Di., 17. Jan. 2017,
8:18 PM:

Okay so you want to use rectangle cards just like other sections. I'll do
this one

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/fossasia/gci16.fossasia.org/issues/969#issuecomment-273252626>,
or mute the thread

**Comment by ankitrgadiya** [comment]
@Elgayar I didn't started it yet. Go for it bro

**Comment by robbyoconnor** [comment]
I want the design of the cards consistent, yes.

**Comment by Elgayar** [comment]
I just got back home, had an exam and an interview. 
Two questions, should I make the students section 6 cards per row, or just make the same design and that's it?
Also, why don't we make the mentors section the same design as well?

**Comment by robbyoconnor** [comment]
All sections should have the same design to look uniform.
